todoapp/tasks/urls.py
from django.urls import path
from todoapp.tasks import views


app_name = 'tasks'

urlpatterns = [
    path('', views.home, name='home'),
    path('<int:task_id>', views.detail, name='detail'),
    path('del/<int:task_id>', views.delete, name='delete'),
]

todoapp/urls.py
from django.contrib import admin
from django.urls import include, path
from todoapp.home_view import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home),
    path('tasks/', include('todoapp.tasks.urls'))
]

todoapp/tasks/models.py
from django.db import models


class Tasks(models.Model):
    name = models.CharField(max_length=128)
    done = models.BooleanField(default=False)

todoapp/tasks/forms.py
from django.forms import ModelForm

from todoapp.tasks.models import Tasks


class NewTaskForm(ModelForm):

    class Meta:
        model = Tasks
        fields = ['name']


class TaskForm(ModelForm):

    class Meta:
        model = Tasks
        fields = ['name', 'done']

todoapp/tasks/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from todoapp.tasks.forms import NewTaskForm, TaskForm
from todoapp.tasks.models import Tasks


def home(request):
    pending_tasks = Tasks.objects.filter(done=False).all()
    done_tasks = Tasks.objects.filter(done=True).all()
    if request.method == 'POST':
        form = NewTaskForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('tasks:home'))
        else:
            return render(request, 'tasks/home.html',
                          {
                              'form': form,
                              'pending_tasks': pending_tasks,
                              'done_tasks': done_tasks
                          },
                          status=400)
    return render(request, 'tasks/home.html',
                  {
                      'pending_tasks': pending_tasks,
                      'done_tasks': done_tasks
                  })


def detail(request, task_id):
    if request.method == 'POST':
        task = Tasks.objects.get(id=task_id)
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            form.save()

    return HttpResponseRedirect(reverse('tasks:home'))


def delete(request, task_id):
    if request.method == 'POST':
        Tasks.objects.filter(id=task_id).delete()
    return HttpResponseRedirect(reverse('tasks:home'))

todoapp/tasks/templates/tasks/home.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Tasks List</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    </head>
    <body>
        <div class="container">
            <div class="row">
                <div class="col-md-8 offset-md-2">
                    <h1 class="mt-5"> Tasks List </h1>

                    <form action="{% url 'tasks:home' %}" method="post">
                        {% csrf_token %}
                        <div class="input-group mb-3">
                            <input type="text" class="form-control" placeholder="Describe the task"
                                    aria-label="Describe the task" aria-describedby="button-addon2" name="name">
                            <button class="btn btn-primary" type="submit" id="button-addon2">Save</button>
                            
                        </div>
                        <small class="form-text text-muted">{{form.name.errors}}</small>
                          
                    </form>

                    <h2 class="mt-5"> Pending Tasks List </h2>
                    {% for task in pending_tasks %}
                        <form action="{% url 'tasks:detail' task_id=task.id %}" method="post">
                            {% csrf_token %}
                            <div class="input-group mb-3">
                                <input type="text" class="form-control" value="{{task.name}}" required="required"
                                aria-label="Describe the task" name="name">

                                <input type="hidden" value="checked" name="done">
                                <button class="btn btn-success" type="submit">Marcar como feita!</button>
                                
                            </div>
                        </form>
                    {% endfor %}

                    <h2 class="mt-5"> Done Tasks List </h2>
                    {% for task in done_tasks %}
                        <div class="row">
                            <div class="col-2">
                                <form action="{% url 'tasks:delete' task_id=task.id %}" method="post">
                                    {% csrf_token %}
                                    <div class="input-group mb-3">
                                        <button class="btn btn-danger" type="submit">Apagar</button>
                                    </div>
                                </form>
                            </div>
                            <div class="col-10">
                                <form action="{% url 'tasks:detail' task_id=task.id %}" method="post">
                                    {% csrf_token %}
                                    <div class="input-group mb-3">
                                        <input type="text" class="form-control" value="{{task.name}}" required="required"
                                        aria-label="Describe the task" name="name">
        
                                        <button class="btn btn-warning" type="submit">Marcar como pendente</button>
                                        
                                    </div>
                                </form>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
    </body>
</html>